### ISSUE TITLE
The program doesnt work!

### ISSUE THREAD

**Issue by Meesmeesie** [raketenben/MinecraftVideoConverter#1]
I cant run it, 1 have a windows 10 pc! can you help me?

**Comment by raketenben** [comment]
Can you provide more Information?

Does the program not open at all or is it something inside the program that doesn't work?
Are you getting any errors?
Did you follow the steps in the instructions?

**Comment by Meesmeesie** [comment]
yes, i click on the .exe file then it does nothing!

**Comment by raketenben** [comment]
I created a new release and updated the instruction accordingly.
Please check if this version works for you (https://github.com/raketenben/MinecraftVideoConverter/releases/tag/v1.1)

**Comment by Meesmeesie** [comment]
Tnhx
