### ISSUE TITLE
Curious,

### ISSUE THREAD

**Issue by Squiee** [raketenben/MinecraftVideoConverter#2]
Is there any way for me to use this on a multiplayer server? I'm unsure how I'd go about converting the video to the server as it's online rather than hosted on my PC

**Comment by raketenben** [comment]
You would have to download the world from your server, add the video to the world locally, and upload the world to your server again. 

There isn't really any other way. Be sure to make a backup of your world, and keep in mind that the time it takes to upload your world, may increase significantly with the video added to your world.
