### ISSUE TITLE
VideoplayerDatapack-1.16-plus

### ISSUE THREAD

**Issue by mybeloonatelo** [raketenben/MinecraftVideoConverter#3]
I tried everything on java to get this to work and all I've been having is issues every time the structure would load in for 1 second and then disappear no blocks just a green square I even tried downloading nbt core v3.4 to fix it and that didn't work either what do I do?

**Comment by raketenben** [comment]
I can't quite follow what is happening on your end. I'm not aware of what  "nbt core" is or what it does. This tool is for vanilla minecraft (1.16-1.20.4 / 1.20.5+), I can't make promises of compatibility with mods or server plugins. The only thing I can advise you to do, is to double-check you got the right version of the data pack for your version.

You can find the two different datapack versions on the [release page](https://github.com/raketenben/MinecraftVideoConverter/releases/tag/v1.1)
![Screenshot 2024-06-11 102210](https://github.com/raketenben/MinecraftVideoConverter/assets/35403861/5f9a955c-b706-47f0-8931-adee29a131ae)

**Comment by mybeloonatelo** [comment]
I tried both no mods nothing all versions idk what's going on.

**Comment by raketenben** [comment]
With this little information, I am unable to help. I hope you figure it out.

**Comment by mybeloonatelo** [comment]
Alright then I'll probably just continue working on my structure block
build instead.
